[project]
name = "gym_sapientino"
description = "Gym Sapientino environment using Pygame."
license = "GPL-3.0-or-later"
keywords = [
    "grid-world",
		"continuous state",
    "reinforcement learning",
    "gymnasium",
]
version = "0.4.0"
dynamic = ["classifiers"]
readme = "README.md"
authors = [{name = "Roberto Cipollone", email = "cipollone@diag.uniroma1.it"}, {name = "Luca Iocchi", email = "iocchi@diag.uniroma1.it"}, {name = "Marco Favorito", email = "favorito@diag.uniroma1.it"}]
requires-python = '>=3.9,<4.0'
dependencies = [
	'gymnasium (>=0.26.1)',
	'numpy (>=1.21.0,<3.0.0)',
	'pygame (>=2.2.0,<3.0.0)',
	'pillow (>=10.1.0,<12.0.0)',
]

[project.urls]
homepage = "https://whitemech.github.io/gym-sapientino"
repository = "https://github.com/whitemech/gym-sapientino.git"
documentation = "https://whitemech.github.io/gym-sapientino"
"Bug Tracker" = "https://github.com/whitemech/gym-sapientino/issues"
"Pull Requests" = "https://github.com/whitemech/gym-sapientino/pulls"

[tool.poetry]
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.11.0"
pytest-cov = "^4.1.0"
pytest-randomly = "^3.15.0"
tox = "^4.9.0"
codecov = "^2.1.13"
isort = "^5.12.0"
bandit = "^1.7.5"
mypy = "^1.7.0"
safety = "^2.3.1"
ipython = "^8.17.2"
notebook = "^7.0.6"
flake8 = "^6.1.0"
mkdocs = "^1.5.3"
ruff-lsp = "^0.0.45"
pyright = "^1.1.335"
markdown-include = "^0.8.1"

[build-system]
requires = ['poetry-core (>=2.0.0,<3.0.0)']
build-backend = "poetry.core.masonry.api"
