# type: ignore
black  # unused variable (gym_sapientino/sapientino_env.py:36)
grey  # unused variable (gym_sapientino/sapientino_env.py:38)
orange  # unused variable (gym_sapientino/sapientino_env.py:39)
red  # unused variable (gym_sapientino/sapientino_env.py:40)
_.observation_space  # unused property (gym_sapientino/sapientino_env.py:322)
metadata  # unused variable (gym_sapientino/sapientino_env.py:650)
_.observation_space  # unused property (gym_sapientino/sapientino_env.py:665)
encode  # unused function (gym_sapientino/utils.py:28)
decode  # unused function (gym_sapientino/utils.py:47)
_.observation_space  # unused property (gym_sapientino/wrappers/dict_space.py:52)
