# type: ignore
DEFAULT_MAP_PATH  # unused variable (gym_sapientino/core/constants.py:31)
black  # unused variable (gym_sapientino/core/constants.py:32)
grey  # unused variable (gym_sapientino/core/constants.py:34)
orange  # unused variable (gym_sapientino/core/constants.py:35)
red  # unused variable (gym_sapientino/core/constants.py:36)
_.position  # unused property (gym_sapientino/core/objects.py:54)
_.from_id  # unused method (gym_sapientino/core/types.py:143)
cls  # unused variable (gym_sapientino/core/types.py:144)
color2id  # unused variable (gym_sapientino/core/types.py:161)
encode  # unused function (gym_sapientino/utils.py:28)
decode  # unused function (gym_sapientino/utils.py:47)
