# type: ignore
black  # unused variable (gym_sapientino/core/constants.py:31)
grey  # unused variable (gym_sapientino/core/constants.py:33)
orange  # unused variable (gym_sapientino/core/constants.py:34)
red  # unused variable (gym_sapientino/core/constants.py:35)
_.position  # unused property (gym_sapientino/core/objects.py:54)
_.from_id  # unused method (gym_sapientino/core/types.py:143)
cls  # unused variable (gym_sapientino/core/types.py:144)
encode  # unused function (gym_sapientino/utils.py:28)
decode  # unused function (gym_sapientino/utils.py:47)
